### ISSUE TITLE
plugin sends update to new version message but its already up to date 

### ISSUE THREAD

**Issue by KeksToGo** [WiIIiam278/DesertWell#1]
![IMG_20230224_000812](https://user-images.githubusercontent.com/67545942/221031180-2a2d366b-4d15-4815-82fd-e8cc2df00093.png)

**Comment by WiIIiam278** [comment]
Closed in https://github.com/WiIIiam278/DesertWell/commit/aea4520277e9c9665caf9af9b55fc0f151e99231
